# Basic Tutorial Overview
## Import 


In [1]:
import numpy as np

---

### 1. Matricies of Type (m x n)

In [13]:
a = np.array([1,2,3])

B = np.array([(1,2,3), 
              (4,5,6)])

C = np.array([(1+0j,2+0j,3+0j), 
              (4+0j,5+0j,6+0j)])

With the print() function you can print out Vector $\vec{a}$ (1x3 matrix):

$
\vec{a} = \left( \begin{array}{rrr}
1 & 2 & 3  \\
\end{array}\right)
$ 

or $B$ (2x3 matrix):

$
B = 
\left(
\begin{array}{rrr}
1 & 2 & 3  \\
4 & 5 & 6  \\
\end{array}
\right)
$

or $C$ (2x3 matrix):

$
C = \left( \begin{array}{rrr}
1+0j & 2+0j & 3+0j  \\
4+0j & 5+0j & 6+0j  \\
\end{array}\right)
$




---

$\vec{a}$ when printed:

In [21]:
print(a)

[1 2 3]


$B$ when printed:

In [19]:
print(b)

[[1 2 3]
 [4 5 6]]


$C$ when printed:

In [16]:
print(c)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


---