# Basic Tutorial Overview
## Import 


In [1]:
import numpy as np

---

## 1. Matricies of Type (m x n)
### i. Real and Complex Matrices

In [22]:
a = np.array([1,2,3])

B = np.array([(1,2,3), 
              (4,5,6)])

C = np.array([(1+0j,2+0j,3+0j), 
              (4+0j,5+0j,6+0j)])

With the print() function you can print out Vector $\vec{a}$:

$
\vec{a} = \left( \begin{array}{rrr}
1 & 2 & 3  \\
\end{array}\right)
$ 

or $B$ (2x3 matrix):

$
B = 
\left(
\begin{array}{rrr}
1 & 2 & 3  \\
4 & 5 & 6  \\
\end{array}
\right)
$

or $C$ (2x3 matrix):

$
C = \left( \begin{array}{rrr}
1+0j & 2+0j & 3+0j  \\
4+0j & 5+0j & 6+0j  \\
\end{array}\right)
$




---

$\vec{a}$ when printed:

In [21]:
print(a)

[1 2 3]


$\vec{a}$ can also be written as $A$ (1x3 matrix):

In [43]:
A = np.asmatrix(a)

$A$ when printed:

In [44]:
print(A)

[[1 2 3]]


$B$ when printed:

In [19]:
print(b)

[[1 2 3]
 [4 5 6]]


$C$ when printed:

In [16]:
print(c)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


---

### ii. Transpose of Matricies

To calculate $A^T$, $B^T$ and $C^T$, use the transpose method (T):



In [45]:
A.T

matrix([[1],
        [2],
        [3]])

In [46]:
B.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
C.T

array([[1.+0.j, 4.+0.j],
       [2.+0.j, 5.+0.j],
       [3.+0.j, 6.+0.j]])

With the print() function you can print out Vector $\vec{a}$:

$
A = (a_{mn}) = \left( \begin{array}{rrr}
1 & 2 & 3  \\
\end{array}\right) \rightarrow
A^T = (a_{nm}) = \left( \begin{array}{r}
1 \\ 
2 \\
3 \\
\end{array}\right)
$ 

$
B = (b_{ij}) = 
\left(
\begin{array}{rrr}
1 & 2 & 3  \\
4 & 5 & 6  \\
\end{array}
\right)\rightarrow
B^T = (b_{mn}) = \left( \begin{array}{rr}
1 & 4 \\ 
2 & 5 \\
3 & 6 \\
\end{array}\right)
$

or $C$ (2x3 matrix):

$
C = \left( \begin{array}{rrr}
1+0j & 2+0j & 3+0j  \\
4+0j & 5+0j & 6+0j  \\
\end{array}\right)
$

In [40]:
np.asmatrix(a).T

matrix([[1],
        [2],
        [3]])

### iii. Adjugate Matrix

In [53]:
A

matrix([[1, 2, 3]])

In [51]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
C

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])